parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        dbname: small_farm
        host: localhost
        port: 3306
        user: root
        password: 
        
        driver: pdo_mysql
        server_version: 'mariadb-10.1.35'
        charset: UTF8
        
        url:                mysql://root:@127.0.0.1:3306/small_farm
        # the DBAL driverClass option
        driver_class:         App\DBAL\MyDatabaseDriver
        # the DBAL driverOptions option
        options:
            foo: bar
        path:                 '%kernel.project_dir%/var/data/data.sqlite'
        memory:               true
        unix_socket:          /tmp/mysql.sock
        

        